/* L'elenco delle destinazioni ATAM, per le pagine.

   L'ORIGINALE e' supabase/functions/richieste/luoghi.ts, che e' anche
   quello che RIFIUTA un luogo fuori elenco. Questa e' una copia perche'
   una pagina HTML non puo' importare un modulo Deno.

   NON si riordina e NON si ripulisce: le voci devono combaciare parola per
   parola col modulo dei tassisti, doppi spazi compresi. La reception
   ricopia il valore, e una voce diversa la costringe a cercarla a mano fra
   189. Lo tiene fermo pagine/comune/luoghi.test.ts. */
export const LUOGHI_ATAM = [
  "Montegrotto",
  "Padova FS",
  "Padova città",
  "Terme  Euganee FS",
  "Treviso Aeroporto",
  "Venezia  aeroporto",
  "Venezia P.le Roma",
  "Venezia porto",
  "Abano",
  "Abano - Montegrotto",
  "Abano F.S",
  "Aeroporto Roma fiumicino",
  "Agugliaro",
  "Albignasego",
  "Anguillara",
  "Ariano ferrarese",
  "Arquà Petrarca",
  "Arzergrande",
  "Ascona",
  "Asiago",
  "Asolo",
  "Assenza corte",
  "Assenza lunghe",
  "Bad KleinKircheim",
  "Badia Polesine",
  "Bagnoli di Sopra",
  "Baone",
  "Bassano del Grappa",
  "Bastia",
  "Battaglia Terme",
  "Belluno",
  "Bergamo aeroporto✈️",
  "Bologna Aeroporto",
  "Bologna città🎯",
  "Bolzano",
  "Bovolenta",
  "Brendola (VI)",
  "Brescia",
  "Brindisi",
  "Cadoneghe",
  "Cagliari",
  "Campodarsego",
  "Camposampiero",
  "Cartura",
  "Casalserugo",
  "Caselle di Selvazzano",
  "Castelfranco",
  "Castello del Catajo",
  "Cervarese Santa Croce",
  "Cesena",
  "Chiasso",
  "Chiasso (ch)",
  "Chioggia-Sottomarina",
  "Cinto Euganeo",
  "Cittadella",
  "Como",
  "Conegliano",
  "Conselve",
  "Cortina D'ampezzo",
  "Courmayeur",
  "Cremona",
  "Due Carrare",
  "Este",
  "Ferrara",
  "Firenze",
  "Folgaria",
  "Formigine",
  "Galzignano",
  "Galzignano e Galz Hotels",
  "Gardone Riviera",
  "Genova",
  "Giro Colli 2 ore🖼",
  "Giro Colli 3 ore🖼",
  "Giro Colli 4 ore🖼",
  "Golf Frassanelle 🏌",
  "Golf Montecchia🏌",
  "Golf Valsanzibio 🏌",
  "Gorizia",
  "Grado",
  "Grisignano",
  "Imola",
  "Imperia",
  "Innsbruck",
  "Ipercity-Albignasego",
  "Jesolo⛱",
  "La Spezia",
  "Legnaro",
  "Lignano Sabbiadoro⛱",
  "Limena",
  "Luvigliano",
  "Mandria opera immacolata",
  "Mantova",
  "Marchirolo",
  "Marostica",
  "Maserà",
  "Mentone",
  "Merano",
  "Mercato Abano",
  "Mercato Montegrotto",
  "Mestre fs",
  "Mestrino",
  "Milano Città🎯",
  "Milano Malpensa✈️",
  "Milano Marittima",
  "Milano-Linate",
  "Mira-Dolo",
  "Modena",
  "Monselice",
  "Montagnana",
  "Montegaldella",
  "Montemerlo",
  "Noventa Padovana",
  "Noventa di Piave👔",
  "Noventa vicentina",
  "Occhiobello",
  "Ortisei",
  "Outlet Noventa 3 ore",
  "Outlet Noventa 4 ore",
  "Palmanova",
  "Parco dei Tigli",
  "Parma",
  "Pavia",
  "Pernumia",
  "Perugia",
  "Pesaro - Urbino",
  "Pescara",
  "Peschiera del Garda",
  "Piacenza",
  "Piazzola sul Brenta",
  "Piove di Sacco",
  "Pisa",
  "Pordenone",
  "Porto Sant' Elpidio",
  "Pozzonovo",
  "Praglia⛪️",
  "Prato",
  "Princ. di Monaco",
  "Ravenna",
  "Reggio Emilia",
  "Rimini",
  "Riva del Garda",
  "Roma",
  "Rovigo",
  "Rovolon",
  "Rubano",
  "Saccolongo",
  "Sacile",
  "San Daniele ⛪️",
  "San Pietro viminario",
  "Santa Giustina in Colle",
  "Saonara",
  "Sarmeola di Rubano",
  "Sassuolo",
  "Schiavonia",
  "Schio",
  "Selvazzano",
  "Sermide",
  "Siena",
  "Sirmione",
  "Solesino",
  "Stanghella",
  "Stra",
  "Tencarola",
  "Teolo",
  "Terassa padovana",
  "Terradura",
  "Torino",
  "Torre di Quartesolo",
  "Torreglia",
  "Tortona",
  "Trento",
  "Tribano",
  "Trieste",
  "Udine",
  "Val Badia",
  "Valsanzibio",
  "Varese",
  "Verona Aeroporto✈️",
  "Verona Arena🌛",
  "Verona città🎯",
  "Vicenza Fiera",
  "Vicenza città🎯",
  "Vienna",
  "Vigonovo",
  "Vigonza",
  "Villafranca Padovana",
  "Vo",
  "Zurigo",
  "civitavecchia",
];

/* LE DUE voci che il modulo transfer del sito mette in prima fila, fuori
   dalla tendina.

   ERANO DODICI fino al 23 agosto 2026, e la proprietà le ha ridotte a
   due: «il più richiesto è Venezia Marco Polo, e magari la stazione dei
   treni di Padova; gli altri metterli in Un'altra destinazione, per
   rendere la schermata più leggera e veloce per il cliente». Dodici
   pastiglie su quattro righe sono un elenco da leggere; due sono una
   scelta da fare.

   LE ALTRE DIECI NON SPARISCONO: la tendina completa si costruisce da
   LUOGHI_ATAM meno queste, quindi tutto quello che esce di qui entra da
   solo dietro «Un'altra destinazione…». Chi in futuro volesse
   riallungare questo elenco non lo "completi" tagliando le prime N voci
   di LUOGHI_ATAM: quelle cominciano con Montegrotto e Padova città, che
   sono a due passi dall'hotel e non sono punti di arrivo per un ospite.

   Ogni voce qui sotto DEVE esistere anche in LUOGHI_ATAM, parola per
   parola: lo tiene fermo luoghi.test.ts. Se i tassisti rinominano una di
   queste destinazioni, la voce sparirebbe in silenzio dal gruppo in
   prima fila — la prova lo scopre invece. */
export const PIU_RICHIESTI = [
  "Venezia  aeroporto",
  "Padova FS",
];

/* L'ICONA di ciascuna, per chi la guarda su un telefono: la chiave e' il
   valore ESATTO di ATAM, doppi spazi compresi, perche' e' quello che il
   modulo ha in mano. Una voce senza icona non e' un errore: esce senza,
   come tutte le altre della tendina. */
export const ICONA_META = {
  "Venezia  aeroporto": "aereo",
  "Padova FS": "treno",
};
