/* L'elenco delle destinazioni ATAM, per le pagine.

   L'ORIGINALE e' supabase/functions/richieste/luoghi.ts, che e' anche
   quello che RIFIUTA un luogo fuori elenco. Questa e' una copia perche'
   una pagina HTML non puo' importare un modulo Deno.

   NON si riordina e NON si ripulisce: le voci devono combaciare parola per
   parola col modulo dei tassisti, doppi spazi compresi. La reception
   ricopia il valore, e una voce diversa la costringe a cercarla a mano fra
   189. Lo tiene fermo pagine/comune/luoghi.test.ts. */
export const LUOGHI_ATAM = [
  "Montegrotto",
  "Padova FS",
  "Padova città",
  "Terme  Euganee FS",
  "Treviso Aeroporto",
  "Venezia  aeroporto",
  "Venezia P.le Roma",
  "Venezia porto",
  "Abano",
  "Abano - Montegrotto",
  "Abano F.S",
  "Aeroporto Roma fiumicino",
  "Agugliaro",
  "Albignasego",
  "Anguillara",
  "Ariano ferrarese",
  "Arquà Petrarca",
  "Arzergrande",
  "Ascona",
  "Asiago",
  "Asolo",
  "Assenza corte",
  "Assenza lunghe",
  "Bad KleinKircheim",
  "Badia Polesine",
  "Bagnoli di Sopra",
  "Baone",
  "Bassano del Grappa",
  "Bastia",
  "Battaglia Terme",
  "Belluno",
  "Bergamo aeroporto✈️",
  "Bologna Aeroporto",
  "Bologna città🎯",
  "Bolzano",
  "Bovolenta",
  "Brendola (VI)",
  "Brescia",
  "Brindisi",
  "Cadoneghe",
  "Cagliari",
  "Campodarsego",
  "Camposampiero",
  "Cartura",
  "Casalserugo",
  "Caselle di Selvazzano",
  "Castelfranco",
  "Castello del Catajo",
  "Cervarese Santa Croce",
  "Cesena",
  "Chiasso",
  "Chiasso (ch)",
  "Chioggia-Sottomarina",
  "Cinto Euganeo",
  "Cittadella",
  "Como",
  "Conegliano",
  "Conselve",
  "Cortina D'ampezzo",
  "Courmayeur",
  "Cremona",
  "Due Carrare",
  "Este",
  "Ferrara",
  "Firenze",
  "Folgaria",
  "Formigine",
  "Galzignano",
  "Galzignano e Galz Hotels",
  "Gardone Riviera",
  "Genova",
  "Giro Colli 2 ore🖼",
  "Giro Colli 3 ore🖼",
  "Giro Colli 4 ore🖼",
  "Golf Frassanelle 🏌",
  "Golf Montecchia🏌",
  "Golf Valsanzibio 🏌",
  "Gorizia",
  "Grado",
  "Grisignano",
  "Imola",
  "Imperia",
  "Innsbruck",
  "Ipercity-Albignasego",
  "Jesolo⛱",
  "La Spezia",
  "Legnaro",
  "Lignano Sabbiadoro⛱",
  "Limena",
  "Luvigliano",
  "Mandria opera immacolata",
  "Mantova",
  "Marchirolo",
  "Marostica",
  "Maserà",
  "Mentone",
  "Merano",
  "Mercato Abano",
  "Mercato Montegrotto",
  "Mestre fs",
  "Mestrino",
  "Milano Città🎯",
  "Milano Malpensa✈️",
  "Milano Marittima",
  "Milano-Linate",
  "Mira-Dolo",
  "Modena",
  "Monselice",
  "Montagnana",
  "Montegaldella",
  "Montemerlo",
  "Noventa Padovana",
  "Noventa di Piave👔",
  "Noventa vicentina",
  "Occhiobello",
  "Ortisei",
  "Outlet Noventa 3 ore",
  "Outlet Noventa 4 ore",
  "Palmanova",
  "Parco dei Tigli",
  "Parma",
  "Pavia",
  "Pernumia",
  "Perugia",
  "Pesaro - Urbino",
  "Pescara",
  "Peschiera del Garda",
  "Piacenza",
  "Piazzola sul Brenta",
  "Piove di Sacco",
  "Pisa",
  "Pordenone",
  "Porto Sant' Elpidio",
  "Pozzonovo",
  "Praglia⛪️",
  "Prato",
  "Princ. di Monaco",
  "Ravenna",
  "Reggio Emilia",
  "Rimini",
  "Riva del Garda",
  "Roma",
  "Rovigo",
  "Rovolon",
  "Rubano",
  "Saccolongo",
  "Sacile",
  "San Daniele ⛪️",
  "San Pietro viminario",
  "Santa Giustina in Colle",
  "Saonara",
  "Sarmeola di Rubano",
  "Sassuolo",
  "Schiavonia",
  "Schio",
  "Selvazzano",
  "Sermide",
  "Siena",
  "Sirmione",
  "Solesino",
  "Stanghella",
  "Stra",
  "Tencarola",
  "Teolo",
  "Terassa padovana",
  "Terradura",
  "Torino",
  "Torre di Quartesolo",
  "Torreglia",
  "Tortona",
  "Trento",
  "Tribano",
  "Trieste",
  "Udine",
  "Val Badia",
  "Valsanzibio",
  "Varese",
  "Verona Aeroporto✈️",
  "Verona Arena🌛",
  "Verona città🎯",
  "Vicenza Fiera",
  "Vicenza città🎯",
  "Vienna",
  "Vigonovo",
  "Vigonza",
  "Villafranca Padovana",
  "Vo",
  "Zurigo",
  "civitavecchia",
];

/* Le dodici voci che il modulo transfer del sito mette in prima fila,
   fuori dalla tendina — NON le prime dodici di LUOGHI_ATAM: sono una
   curatela, non un taglio meccanico dell'elenco. Sono i punti da cui un
   ospite ARRIVA (aeroporti, stazioni, il porto) piu' i tre campi da golf
   convenzionati, perche' sono le destinazioni piu' richieste davvero. Chi
   in futuro la vede corta non deve "completarla" fino a farla combaciare
   con LUOGHI_ATAM: le prime otto di quell'elenco cominciano con
   Montegrotto e Padova città, che sono a due passi dall'hotel e non sono
   punti di arrivo per un ospite.

   Ogni voce qui sotto DEVE esistere anche in LUOGHI_ATAM, parola per
   parola: lo tiene fermo luoghi.test.ts. Se i tassisti rinominano una di
   queste destinazioni, la voce sparirebbe in silenzio dal gruppo in
   prima fila — la prova lo scopre invece. */
export const PIU_RICHIESTI = [
  "Venezia  aeroporto",
  "Treviso Aeroporto",
  "Verona Aeroporto✈️",
  "Bologna Aeroporto",
  "Venezia P.le Roma",
  "Venezia porto",
  "Padova FS",
  "Terme  Euganee FS",
  "Mestre fs",
  "Golf Valsanzibio 🏌",
  "Golf Montecchia🏌",
  "Golf Frassanelle 🏌",
];
