/* I testi della pagina Day Spa, quattro lingue con le stesse chiavi
   (testi.test.ts lo controlla). Nessun prezzo qui: i prezzi arrivano dal
   server. Le parole degli stati sono le stesse cinque che il server sa
   dire (dayspa/posti.ts): chiuso, non-in-vendita, esaurito, ultimi,
   disponibile. */
'use strict';

export const T = {
  it: {
    occhiello: 'Day Spa', titolo: 'Una giornata alle piscine termali',
    sotto: 'Scelga il giorno, la fascia e quante persone: paga online e riceve il biglietto con il QR per email.',
    quando: 'Quando', quandoGuida: 'Scelga il giorno e la fascia.',
    orizzonte: 'Si prenota fino a 7 giorni prima. I posti dipendono dal tempo e da quanti ospiti ha l\'hotel: li apriamo giorno per giorno, e qui vede quelli già in vendita.',
    giorno: 'Giorno', fascia: 'Fascia', scegliGiorno: 'Scelga il giorno', scegliFascia: 'Scelga la fascia',
    fasce: { giornaliero: 'Ingresso giornaliero', serale: 'Ingresso serale' },
    stati: { chiuso: 'chiusi', 'non-in-vendita': 'non ancora in vendita', esaurito: 'esaurito', ultimi: 'ultimi posti', disponibile: 'disponibile' },
    chi: 'Chi viene', chiGuida: 'Bambini dai 2 anni compresi. I neonati fino a 1 anno entrano gratis e non vanno contati.',
    adulti: 'Adulti', bambini: 'Bambini dai 2 anni', neonati: 'Neonati fino a 1 anno: gratis, non li conti.',
    aPersona: 'a persona', totale: 'Totale', persone: (n) => n === 1 ? '1 persona' : `${n} persone`,
    massimo: (n) => `Al massimo ${n} persone per prenotazione: per un gruppo scriva alla reception.`,
    dati: 'I suoi dati', datiGuida: 'Il biglietto arriva a questo indirizzo email.',
    nome: 'Nome e cognome', email: 'Email', telefono: 'Cellulare (facoltativo)',
    consenso: 'Ho letto l\'informativa sulla privacy e accetto che i dati servano a gestire la prenotazione.',
    nonRimborsabile: 'L\'ingresso non è rimborsabile e non si può modificare.',
    paga: 'Paga', pagaAttesa: 'Un momento…',
    erroreCampi: 'Manca qualcosa: controlli i campi segnati.', erroreEmail: 'L\'indirizzo email non sembra giusto.',
    erroreConsenso: 'Serve il consenso per procedere.',
    erroreServer: 'Non riesco a procedere in questo momento. Riprovi tra qualche minuto, o chiami la reception: +39 049 9939200.',
    esauritoNelFrattempo: 'Nel frattempo i posti sono finiti: scelga un altro giorno o un\'altra fascia.',
    nonDisponibile: 'Quel giorno non è prenotabile.',
    grazieTitolo: 'Grazie', grazieAttesa: 'Stiamo aspettando la conferma del pagamento…',
    grazieOk: 'Pagamento ricevuto. Il biglietto con il QR è nella sua email: lo mostri alla reception il giorno dell\'ingresso.',
    grazieProblema: 'Il pagamento non risulta ancora confermato. Se ha pagato, il biglietto arriva a breve; altrimenti ci chiami: +39 049 9939200.',
    grazieNumero: 'Numero della prenotazione',
    prova: 'Pagina di prova: i pagamenti sono finti e le prenotazioni non valgono.',
    provaChiusa: 'Questa pagina è in prova e non è ancora aperta al pubblico.',
    pie: 'Hotel Terme Leonardo · Via Monteortone, 46 · 35037 Monteortone di Abano Terme (PD) · +39 049 9939200 · info@termeleonardo.com',
  },
  de: {
    occhiello: 'Day Spa', titolo: 'Ein Tag in den Thermalbecken',
    sotto: 'Wählen Sie Tag, Zeitfenster und Personenzahl: Sie zahlen online und erhalten das Ticket mit QR-Code per E-Mail.',
    quando: 'Wann', quandoGuida: 'Wählen Sie Tag und Zeitfenster.',
    orizzonte: 'Buchbar bis 7 Tage im Voraus. Die Plätze hängen vom Wetter und von der Belegung des Hotels ab: wir geben sie Tag für Tag frei, hier sehen Sie die bereits verfügbaren.',
    giorno: 'Tag', fascia: 'Zeitfenster', scegliGiorno: 'Tag wählen', scegliFascia: 'Zeitfenster wählen',
    fasce: { giornaliero: 'Tageseintritt', serale: 'Abendeintritt' },
    stati: { chiuso: 'geschlossen', 'non-in-vendita': 'noch nicht im Verkauf', esaurito: 'ausverkauft', ultimi: 'letzte Plätze', disponibile: 'verfügbar' },
    chi: 'Wer kommt', chiGuida: 'Kinder ab 2 Jahren zählen mit. Babys bis 1 Jahr haben freien Eintritt und werden nicht gezählt.',
    adulti: 'Erwachsene', bambini: 'Kinder ab 2 Jahren', neonati: 'Babys bis 1 Jahr: kostenlos, nicht mitzählen.',
    aPersona: 'pro Person', totale: 'Gesamt', persone: (n) => n === 1 ? '1 Person' : `${n} Personen`,
    massimo: (n) => `Höchstens ${n} Personen pro Buchung: für Gruppen schreiben Sie bitte der Rezeption.`,
    dati: 'Ihre Daten', datiGuida: 'Das Ticket kommt an diese E-Mail-Adresse.',
    nome: 'Vor- und Nachname', email: 'E-Mail', telefono: 'Mobilnummer (optional)',
    consenso: 'Ich habe die Datenschutzerklärung gelesen und bin einverstanden, dass die Daten zur Abwicklung der Buchung verwendet werden.',
    nonRimborsabile: 'Der Eintritt ist nicht erstattungsfähig und nicht änderbar.',
    paga: 'Bezahlen', pagaAttesa: 'Einen Moment…',
    erroreCampi: 'Es fehlt etwas: bitte prüfen Sie die markierten Felder.', erroreEmail: 'Die E-Mail-Adresse scheint nicht zu stimmen.',
    erroreConsenso: 'Ohne Einverständnis geht es nicht weiter.',
    erroreServer: 'Im Moment geht es nicht weiter. Versuchen Sie es in ein paar Minuten noch einmal oder rufen Sie die Rezeption an: +39 049 9939200.',
    esauritoNelFrattempo: 'Inzwischen sind die Plätze weg: wählen Sie bitte einen anderen Tag oder ein anderes Zeitfenster.',
    nonDisponibile: 'Dieser Tag ist nicht buchbar.',
    grazieTitolo: 'Danke', grazieAttesa: 'Wir warten auf die Zahlungsbestätigung…',
    grazieOk: 'Zahlung erhalten. Das Ticket mit dem QR-Code ist in Ihrer E-Mail: zeigen Sie es am Tag des Besuchs an der Rezeption.',
    grazieProblema: 'Die Zahlung ist noch nicht bestätigt. Wenn Sie bezahlt haben, kommt das Ticket in Kürze; sonst rufen Sie uns an: +39 049 9939200.',
    grazieNumero: 'Buchungsnummer',
    prova: 'Testseite: die Zahlungen sind nicht echt und die Buchungen gelten nicht.',
    provaChiusa: 'Diese Seite ist im Test und noch nicht öffentlich.',
    pie: 'Hotel Terme Leonardo · Via Monteortone, 46 · 35037 Monteortone di Abano Terme (PD) · +39 049 9939200 · info@termeleonardo.com',
  },
  en: {
    occhiello: 'Day Spa', titolo: 'A day at the thermal pools',
    sotto: 'Choose the day, the time slot and how many people: pay online and receive the ticket with a QR code by email.',
    quando: 'When', quandoGuida: 'Choose the day and the time slot.',
    orizzonte: 'Bookable up to 7 days ahead. Places depend on the weather and on how full the hotel is: we open them day by day, and here you see those already on sale.',
    giorno: 'Day', fascia: 'Time slot', scegliGiorno: 'Choose the day', scegliFascia: 'Choose the time slot',
    fasce: { giornaliero: 'Day entry', serale: 'Evening entry' },
    stati: { chiuso: 'closed', 'non-in-vendita': 'not yet on sale', esaurito: 'sold out', ultimi: 'last places', disponibile: 'available' },
    chi: 'Who is coming', chiGuida: 'Children from 2 years count. Babies up to 1 year enter free and are not counted.',
    adulti: 'Adults', bambini: 'Children from 2 years', neonati: 'Babies up to 1 year: free, do not count them.',
    aPersona: 'per person', totale: 'Total', persone: (n) => n === 1 ? '1 person' : `${n} people`,
    massimo: (n) => `At most ${n} people per booking: for a group please write to reception.`,
    dati: 'Your details', datiGuida: 'The ticket is sent to this email address.',
    nome: 'Full name', email: 'Email', telefono: 'Mobile (optional)',
    consenso: 'I have read the privacy notice and agree that my details are used to handle the booking.',
    nonRimborsabile: 'Entry is non-refundable and cannot be changed.',
    paga: 'Pay', pagaAttesa: 'One moment…',
    erroreCampi: 'Something is missing: please check the marked fields.', erroreEmail: 'The email address does not look right.',
    erroreConsenso: 'Consent is needed to continue.',
    erroreServer: 'We cannot proceed right now. Please try again in a few minutes, or call reception: +39 049 9939200.',
    esauritoNelFrattempo: 'The places have just sold out: please choose another day or time slot.',
    nonDisponibile: 'That day cannot be booked.',
    grazieTitolo: 'Thank you', grazieAttesa: 'Waiting for the payment confirmation…',
    grazieOk: 'Payment received. The ticket with the QR code is in your email: show it at reception on the day.',
    grazieProblema: 'The payment is not confirmed yet. If you paid, the ticket is on its way; otherwise please call us: +39 049 9939200.',
    grazieNumero: 'Booking number',
    prova: 'Test page: payments are not real and bookings are not valid.',
    provaChiusa: 'This page is being tested and is not open yet.',
    pie: 'Hotel Terme Leonardo · Via Monteortone, 46 · 35037 Monteortone di Abano Terme (PD) · +39 049 9939200 · info@termeleonardo.com',
  },
  fr: {
    occhiello: 'Day Spa', titolo: 'Une journée aux piscines thermales',
    sotto: 'Choisissez le jour, le créneau et le nombre de personnes : vous payez en ligne et recevez le billet avec QR code par e-mail.',
    quando: 'Quand', quandoGuida: 'Choisissez le jour et le créneau.',
    orizzonte: 'Réservable jusqu\'à 7 jours à l\'avance. Les places dépendent de la météo et du taux d\'occupation de l\'hôtel : nous les ouvrons jour après jour, et vous voyez ici celles déjà en vente.',
    giorno: 'Jour', fascia: 'Créneau', scegliGiorno: 'Choisissez le jour', scegliFascia: 'Choisissez le créneau',
    fasce: { giornaliero: 'Entrée journée', serale: 'Entrée soirée' },
    stati: { chiuso: 'fermé', 'non-in-vendita': 'pas encore en vente', esaurito: 'complet', ultimi: 'dernières places', disponibile: 'disponible' },
    chi: 'Qui vient', chiGuida: 'Les enfants dès 2 ans comptent. Les bébés jusqu\'à 1 an entrent gratuitement et ne sont pas comptés.',
    adulti: 'Adultes', bambini: 'Enfants dès 2 ans', neonati: 'Bébés jusqu\'à 1 an : gratuit, ne les comptez pas.',
    aPersona: 'par personne', totale: 'Total', persone: (n) => n === 1 ? '1 personne' : `${n} personnes`,
    massimo: (n) => `Au maximum ${n} personnes par réservation : pour un groupe, écrivez à la réception.`,
    dati: 'Vos coordonnées', datiGuida: 'Le billet est envoyé à cette adresse e-mail.',
    nome: 'Nom et prénom', email: 'E-mail', telefono: 'Portable (facultatif)',
    consenso: 'J\'ai lu la politique de confidentialité et j\'accepte que mes données servent à gérer la réservation.',
    nonRimborsabile: 'L\'entrée est non remboursable et non modifiable.',
    paga: 'Payer', pagaAttesa: 'Un instant…',
    erroreCampi: 'Il manque quelque chose : vérifiez les champs signalés.', erroreEmail: 'L\'adresse e-mail ne semble pas correcte.',
    erroreConsenso: 'Le consentement est nécessaire pour continuer.',
    erroreServer: 'Impossible de continuer pour le moment. Réessayez dans quelques minutes ou appelez la réception : +39 049 9939200.',
    esauritoNelFrattempo: 'Les places viennent de partir : choisissez un autre jour ou un autre créneau.',
    nonDisponibile: 'Ce jour ne peut pas être réservé.',
    grazieTitolo: 'Merci', grazieAttesa: 'Nous attendons la confirmation du paiement…',
    grazieOk: 'Paiement reçu. Le billet avec le QR code est dans votre e-mail : présentez-le à la réception le jour de l\'entrée.',
    grazieProblema: 'Le paiement n\'est pas encore confirmé. Si vous avez payé, le billet arrive sous peu ; sinon appelez-nous : +39 049 9939200.',
    grazieNumero: 'Numéro de réservation',
    prova: 'Page de test : les paiements sont fictifs et les réservations ne sont pas valables.',
    provaChiusa: 'Cette page est en test et pas encore ouverte au public.',
    pie: 'Hotel Terme Leonardo · Via Monteortone, 46 · 35037 Monteortone di Abano Terme (PD) · +39 049 9939200 · info@termeleonardo.com',
  },
};
