/* ============================================================
   opinione.js — le parole del percorso «La sua opinione» sul totem, nelle
   quattro lingue dell'hotel. Modulo puro: lo prova opinione.test.ts.
   L'ordine dei temi e' quello della funzione (opinione.ts).
   ============================================================ */
export const TEMI_OPINIONE = ['camera', 'cure', 'piscine', 'ristorante', 'personale', 'pulizia', 'prezzo'];

const TESTI = {
  it: {
    scegliLingua: 'Scelga la lingua',
    stelleTitolo: 'Come è andata?',
    stelleSotto: 'Tocchi le stelle',
    temiBene: 'Cosa le è piaciuto?',
    temiMale: 'Cosa possiamo migliorare?',
    commentoTitolo: 'Vuole aggiungere qualcosa?',
    commentoSotto: 'Facoltativo',
    salta: 'Salta',
    avanti: 'Avanti',
    indietro: 'Indietro',
    chiTitolo: 'Chi è?',
    chiTessera: 'Se desidera una risposta, passi la tessera della camera al lettore.',
    chiAnonimo: 'Resto anonimo',
    invio: 'Un momento…',
    grazie: 'Grazie',
    grazieTesto: 'La sua opinione è arrivata alla direzione.',
    google: 'Se le va, lo dica anche su Google.',
    errore: 'Non sono riuscito a mandare la sua opinione: lo dica alla reception, qui accanto.',
    privacy: 'Usiamo la sua opinione solo per rispondere e per migliorare. Dalla tessera prendiamo solo il numero di camera.',
    temi: { camera: 'Camera', cure: 'Cure termali', piscine: 'Piscine e spa', ristorante: 'Ristorante', personale: 'Personale', pulizia: 'Pulizia', prezzo: 'Prezzo' },
  },
  en: {
    scegliLingua: 'Choose your language',
    stelleTitolo: 'How was it?',
    stelleSotto: 'Tap the stars',
    temiBene: 'What did you like?',
    temiMale: 'What could we do better?',
    commentoTitolo: 'Anything to add?',
    commentoSotto: 'Optional',
    salta: 'Skip',
    avanti: 'Next',
    indietro: 'Back',
    chiTitolo: 'Who are you?',
    chiTessera: 'If you would like a reply, hold your room key card up to the reader.',
    chiAnonimo: 'Stay anonymous',
    invio: 'One moment…',
    grazie: 'Thank you',
    grazieTesto: 'Your feedback has reached the management.',
    google: 'If you like, say it on Google too.',
    errore: 'We could not send your feedback: please tell the reception desk, right here.',
    privacy: 'We use your feedback only to reply and to improve. From the card we take only the room number.',
    temi: { camera: 'Room', cure: 'Thermal treatments', piscine: 'Pools and spa', ristorante: 'Restaurant', personale: 'Staff', pulizia: 'Cleanliness', prezzo: 'Price' },
  },
  de: {
    scegliLingua: 'Wählen Sie Ihre Sprache',
    stelleTitolo: 'Wie war es?',
    stelleSotto: 'Tippen Sie auf die Sterne',
    temiBene: 'Was hat Ihnen gefallen?',
    temiMale: 'Was können wir besser machen?',
    commentoTitolo: 'Möchten Sie etwas hinzufügen?',
    commentoSotto: 'Freiwillig',
    salta: 'Überspringen',
    avanti: 'Weiter',
    indietro: 'Zurück',
    chiTitolo: 'Wer sind Sie?',
    chiTessera: 'Wenn Sie eine Antwort wünschen, halten Sie Ihre Zimmerkarte vor den Leser.',
    chiAnonimo: 'Anonym bleiben',
    invio: 'Einen Moment…',
    grazie: 'Danke',
    grazieTesto: 'Ihre Meinung ist bei der Direktion angekommen.',
    google: 'Wenn Sie möchten, sagen Sie es auch auf Google.',
    errore: 'Ihre Meinung konnte nicht gesendet werden: bitte sagen Sie es an der Rezeption, gleich nebenan.',
    privacy: 'Wir nutzen Ihre Meinung nur, um zu antworten und besser zu werden. Von der Karte nehmen wir nur die Zimmernummer.',
    temi: { camera: 'Zimmer', cure: 'Kuranwendungen', piscine: 'Pools und Spa', ristorante: 'Restaurant', personale: 'Personal', pulizia: 'Sauberkeit', prezzo: 'Preis' },
  },
  fr: {
    scegliLingua: 'Choisissez votre langue',
    stelleTitolo: 'Comment ça s’est passé ?',
    stelleSotto: 'Touchez les étoiles',
    temiBene: 'Qu’avez-vous aimé ?',
    temiMale: 'Que pouvons-nous améliorer ?',
    commentoTitolo: 'Souhaitez-vous ajouter quelque chose ?',
    commentoSotto: 'Facultatif',
    salta: 'Passer',
    avanti: 'Suivant',
    indietro: 'Retour',
    chiTitolo: 'Qui êtes-vous ?',
    chiTessera: 'Si vous souhaitez une réponse, présentez votre carte de chambre au lecteur.',
    chiAnonimo: 'Rester anonyme',
    invio: 'Un instant…',
    grazie: 'Merci',
    grazieTesto: 'Votre avis est arrivé à la direction.',
    google: 'Si vous le souhaitez, dites-le aussi sur Google.',
    errore: 'Nous n’avons pas pu envoyer votre avis : merci de le dire à la réception, juste à côté.',
    privacy: 'Nous utilisons votre avis uniquement pour répondre et nous améliorer. De la carte nous ne prenons que le numéro de chambre.',
    temi: { camera: 'Chambre', cure: 'Soins thermaux', piscine: 'Piscines et spa', ristorante: 'Restaurant', personale: 'Personnel', pulizia: 'Propreté', prezzo: 'Prix' },
  },
};

/** Le parole nella lingua scelta; una lingua sconosciuta parla italiano. */
export function testiOpinione(lingua) {
  return TESTI[lingua] || TESTI.it;
}
